name: baseproject
description: A new Flutter project.

version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.4.5
  get_it: ^4.0.2
  equatable: ^1.1.1
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.7
  dartz: ^0.9.0
  flutter_svg: ^0.17.4
  flutter_masked_text: ^0.8.0
  cpf_cnpj_validator: ^1.0.5
  flutter_secure_storage: ^3.3.3
  dio: ^3.0.9
  esys_flutter_share: ^1.0.2
  shimmer: ^1.1.1
  intl: ^0.16.0
  path_provider: ^1.6.7
  built_value: ^7.1.0
  rxdart: ^0.24.0
  sealed_unions: ^3.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.9.0
  auto_route_generator: ^0.4.8
  built_value_generator: ^7.1.0
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  image: assets/logo.png
  color: "#CBCBCB"

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/logo.svg
    - assets/logo.png

  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Black.ttf
        - asset: fonts/NunitoSans-Bold.ttf
        - asset: fonts/NunitoSans-BoldItalic.ttf
        - asset: fonts/NunitoSans-ExtraBold.ttf
        - asset: fonts/NunitoSans-Light.ttf
        - asset: fonts/NunitoSans-LightItalic.ttf
        - asset: fonts/NunitoSans-Regular.ttf
        - asset: fonts/NunitoSans-SemiBold.ttf
        - asset: fonts/NunitoSans-SemiBoldItalic.ttf
